FROM fedora:39

RUN dnf install -y qt5-qtmultimedia-devel qt5-qtserialport-devel qt5-linguist\
    boost-devel fftw-devel readline-devel systemd-devel libusb1-devel\
    portaudio-devel patch gcc g++ gfortran cmake git asciidoc texinfo\
    rpmdevtools rpmlint
