name: Build packages
on: [push]

env:
  TARGET: package

jobs:
  download_wsjtx:
    runs-on: ubuntu-latest
    steps:
      - name: Downlaod source code
        run: wget https://physics.princeton.edu/pulsar/k1jt/wsjtx-2.5.4.tgz

      - name: Save WSJTX for next jobs
        uses: actions/upload-artifact@v2
        with:
          name: wsjtx-source-code
          path: ${{runner.workspace}}/wsjtx-2.5.4.tgz

  build_focal:
    needs: ['download_wsjtx']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Create Docker Image
        run: cd $GITHUB_WORKSPACE/docker/ubuntu20.04 && docker build . --tag ubuntu_focal_build

      - name: Run Container
        run: docker run --name build -v $GITHUB_WORKSPACE:/tmp ubuntu_focal_build ps uax
