name: Build dev packages
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'windows'

jobs:
  download_wsjtx:
    runs-on: ubuntu-latest
    steps:
      - name: Downlaod source code
        run: wget https://wsjt.sourceforge.io/downloads/wsjtx-2.6.1.tgz

      - name: Save WSJTX for next jobs
        uses: actions/upload-artifact@v2
        with:
          name: wsjtx-source-code
          path: wsjtx-2.6.1.tgz


  patch_source:
    needs: ['download_wsjtx']
    runs-on: ubuntu-latest
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Get source code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wsjtx-source-code

      - name: Unpack the source
        run: mkdir unpack && pwd && ls -l && tar -xzvf wsjtx-2.6.1.tgz -C unpack/

      - name: Prepare source
        run: mkdir newsrc && tar -xzvf unpack/wsjtx-2.6.1/src/wsjtx.tgz -C newsrc/

      - name: Patch WSJTX
        run: cp -R patch/* newsrc/wsjtx/

      - name: Repack source
        run: cd newsrc/ && tar -czvf wsjtx.tgz * && cd ..

      - name: Copy package
        run: cp newsrc/wsjtx.tgz unpack/wsjtx-2.6.1/src/

      - name: Generate md5sum
        run: cd unpack/wsjtx-2.6.1/src/ && md5sum wsjtx.tgz > wsjtx.tgz.md5sum

      - name: Create new archive
        run: cd unpack/ && tar -czvf wsjtx-patched-2.6.1.tgz *

      - name: Upload new patched archive
        uses: actions/upload-artifact@v2
        with:
          name: wsjtx-patched-code
          path: unpack/wsjtx-patched-2.6.1.tgz

  build_rpi64:
    needs: ['patch_source']
    runs-on: [ self-hosted , Linux , ARM64 ]
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wsjtx-patched-code

      - name: Prepare environment
        run: tar -xzvf wsjtx-patched-2.6.1.tgz && mkdir build

      - name: Prepare Makefile
        run: cd build && cmake -DWSJT_SKIP_MANPAGES=ON -DWSJT_GENERATE_DOCS=OFF ../wsjtx-2.6.1

      - name: Compile binaray and create package
        run: cd build && cmake --build . --target package -- -j3

      - name: Upload new patched archive
        uses: actions/upload-artifact@v2
        with:
          name: wsjtx-rpi64-package
          path: build/wsjtx-prefix/src/wsjtx-build/wsjtx_2.6.1_arm64.deb

  build_jammy:
    needs: ['patch_source']
    runs-on: [ self-hosted , Linux , X64 ]
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Get source code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wsjtx-patched-code

      - name: Create Docker Image
        run: cd $GITHUB_WORKSPACE/docker/ubuntu_jammy && docker build . --tag ubuntu_jammy_build

      - name: Run Container
        run: docker run -t -v $GITHUB_WORKSPACE:/build -w /build ubuntu_jammy_build /build/docker/ubuntu_jammy/build.sh

      - name: Upload new patched archive
        uses: actions/upload-artifact@v2
        with:
          name: wsjtx-jammy-package
          path: wsjtx_2.6.1_jammy_amd64.deb

  build_bookworm:
    needs: ['patch_source']
    runs-on: [ self-hosted , Linux , X64 ]
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Get source code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wsjtx-patched-code

      - name: Create Docker Image
        run: cd $GITHUB_WORKSPACE/docker/debian_bookworm && docker build . --tag debian_bookworm_build

      - name: Run Container
        run: docker run -t -v $GITHUB_WORKSPACE:/build -w /build debian_bookworm_build /build/docker/debian_bookworm/build.sh

      - name: Upload new patched archive
        uses: actions/upload-artifact@v2
        with:
          name: wsjtx-bookworm-package
          path: wsjtx_2.6.1_bookworm_amd64.deb

  build_fedora39:
    needs: ['patch_source']
    runs-on: [ self-hosted , Linux , X64 ]
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Get source code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wsjtx-patched-code

      - name: Create Docker Image
        run: cd $GITHUB_WORKSPACE/docker/fedora_39 && docker build . --tag fedora_39_build

      - name: Run Container
        run: docker run -t -v $GITHUB_WORKSPACE:/build -w /build fedora_39_build /build/docker/fedora_39/build.sh

      - name: Upload new patched archive
        uses: actions/upload-artifact@v2
        with:
          name: wsjtx-fedora39-package
          path: wsjtx-2.6.1.fc39.x86_64.rpm

  release_draft:
    needs: ['build_jammy' , 'build_rpi64' , 'build_bookworm' , 'build_fedora39']
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release draft
        uses: actions/create-release@v1
        id: create_release_draft
        with:
          draft: true
          prerelease: true
          release_name: Development build ${{ github.run_number }}
          tag_name: ${{ github.ref }}
          body: |
            Automatic build on push. This is not a release.
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload jammy artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: wsjtx-jammy-package/wsjtx_2.6.1_jammy_amd64.deb
          asset_name: wsjtx_2.6.1_jammy_amd64.deb
          asset_content_type: application/gzip

      - name: upload bookworm artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: wsjtx-buster-package/wsjtx_2.6.1_bookworm_amd64.deb
          asset_name: wsjtx_2.6.1_bookworm_amd64.deb
          asset_content_type: application/gzip

      - name: upload fedora39 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: wsjtx-fedora39-package/wsjtx-2.6.1.fc39.x86_64.rpm
          asset_name: wsjtx-2.6.1.fc39.x86_64.rpm
          asset_content_type: application/gzip

      - name: upload rpi64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: wsjtx-rpi64-package/wsjtx_2.6.1_arm64.deb
          asset_name: wsjtx_2.6.1_arm64.deb
          asset_content_type: application/gzip

      - name: upload patched source code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: wsjtx-patched-code/wsjtx-patched-2.6.1.tgz
          asset_name: wsjtx-patched-2.6.1.tgz
          asset_content_type: application/gzip

  clean_artifacts:
    needs: ['release_draft']
    runs-on: ubunut-latest
    steps:
      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: |
            wsjtx-patched-code
            wsjtx-source-code
            wsjtx-jammy-package
            wsjtx-bookworm-package
            wsjtx-fedora39-package
            wsjtx-rpi64-package
